### ISSUE TITLE
SegmentCellsNuclei resize issues

### ISSUE THREAD

**Issue by jbernitz** [fish-quant/segmentation#19]
I've been using the segmentation algorithm for the past few weeks, and it has worked very well! But as of yesterday I wasn't able to segment my images anymore. It looks like the code has been updated in regards to specifying resizing of images, and this is where I'm encountering issues.  I'm working with 2048x2048 .tif stacks. My last segmentation attempt was on Oct. 4th, 2020, and it worked fine for my images without resizing. However, now if I run the code without specifying resizing I get the following error:

```
{ "type": "SegmentCellsNuclei", "path_scan": "N:\\schroeder\\Data\\JMB\\2020\\201007 Gata1 test 13\\Images\\Raw\\Stacks", "input_subfolder": "", "path_save": "N:\\schroeder\\Data\\JMB\\2020\\201007 Gata1 test 13\\Images\\Analysis\\Segmentation", "str_cyto": "c03", "str_nuclei": "c01", "new_size": "", "size_cells": 140, "size_nuclei": 90, "img_ext": ".tif" }

Function (segment_obj_indiv) called with: {'path_scan': 'N:\\schroeder\\Data\\JMB\\2020\\201007 Gata1 test 13\\Images\\Raw\\Stacks', 'strings': ('c03', 'c01'), 'img_ext': '.tif', 'new_size': (), 'sizes': (140, 90), 'models': ('cyto', 'nuclei'), 'path_save': 'N:\\schroeder\\Data\\JMB\\2020\\201007 Gata1 test 13\\Images\\Analysis\\Segmentation', 'input_subfolder': '', 'callback_log': '<function RPC._gen_remote_method.<locals>.remote_method at 0x000001FECBE8DC18>', 'callback_status': '<function RPC._gen_remote_method.<locals>.remote_method at 0x000001FECBE84048>', 'callback_progress': '<function RPC._gen_remote_method.<locals>.remote_method at 0x000001FECBE8DF78>'}

CellPose will be USING CPU

Loading image pairs and segment them on the fly

Loading images and segment them on the fly

Segmenting image : 201009_MkPsFull_p001_c03.tif

Performing segmentation of cells

Error: Error: Traceback (most recent call last): File "<ipython-input-2-d3ee6e66ac6a>", line 87, in run callback_progress=api.showProgress) File "c:\users\jbernitz\anaconda3\envs\fqseg\lib\site-packages\segwrap\utils_cellpose.py", line 434, in segment_cells_nuclei_indiv cellpose_predict(data_cyto, config_cyto, path_save=path_save_results, callback_log=callback_log) File "c:\users\jbernitz\anaconda3\envs\fqseg\lib\site-packages\segwrap\utils_cellpose.py", line 85, in cellpose_predict masks, flows, styles, diams = model.eval(imgs, diameter=obj_size, channels=channels, net_avg=False, threshold=0.4) File "c:\users\jbernitz\anaconda3\envs\fqseg\lib\site-packages\cellpose\models.py", line 157, in eval threshold=0.4) File "c:\users\jbernitz\anaconda3\envs\fqseg\lib\site-packages\cellpose\models.py", line 296, in eval x = [transforms.reshape(x[i], channels=channels[i], invert=invert) for i in range(nimg)] File "c:\users\jbernitz\anaconda3\envs\fqseg\lib\site-packages\cellpose\models.py", line 296, in <listcomp> x = [transforms.reshape(x[i], channels=channels[i], invert=invert) for i in range(nimg)] File "c:\users\jbernitz\anaconda3\envs\fqseg\lib\site-packages\cellpose\transforms.py", line 191, in reshape data = data.astype(np.float32) MemoryError
```

Because I'm using large images, I decided to try resizing. I saw that the code was updated so that a single integer could be entered. If I enter a single resize value (4; ie 2048x2048 -> 512 x 512) I get the following error:

```
{ "type": "SegmentCellsNuclei", "path_scan": "N:\\schroeder\\Data\\JMB\\2020\\201007 Gata1 test 13\\Images\\Raw\\Stacks", "input_subfolder": "", "path_save": "N:\\schroeder\\Data\\JMB\\2020\\201007 Gata1 test 13\\Images\\Analysis\\Segmentation", "str_cyto": "c03", "str_nuclei": "c01", "new_size": "4", "size_cells": 140, "size_nuclei": 90, "img_ext": ".tif" }

Function (segment_obj_indiv) called with: {'path_scan': 'N:\\schroeder\\Data\\JMB\\2020\\201007 Gata1 test 13\\Images\\Raw\\Stacks', 'strings': ('c03', 'c01'), 'img_ext': '.tif', 'new_size': (4,), 'sizes': (140, 90), 'models': ('cyto', 'nuclei'), 'path_save': 'N:\\schroeder\\Data\\JMB\\2020\\201007 Gata1 test 13\\Images\\Analysis\\Segmentation', 'input_subfolder': '', 'callback_log': '<function RPC._gen_remote_method.<locals>.remote_method at 0x000001FECBE8DC18>', 'callback_status': '<function RPC._gen_remote_method.<locals>.remote_method at 0x000001FECBE84048>', 'callback_progress': '<function RPC._gen_remote_method.<locals>.remote_method at 0x000001FECBE8DF78>'}

CellPose will be USING CPU

Loading image pairs and segment them on the fly

Loading images and segment them on the fly

Segmenting image : 201009_MkPsFull_p001_c03.tif

Performing segmentation of cells

Error: Error: Traceback (most recent call last): File "<ipython-input-2-d3ee6e66ac6a>", line 87, in run callback_progress=api.showProgress) File "c:\users\jbernitz\anaconda3\envs\fqseg\lib\site-packages\segwrap\utils_cellpose.py", line 434, in segment_cells_nuclei_indiv cellpose_predict(data_cyto, config_cyto, path_save=path_save_results, callback_log=callback_log) File "c:\users\jbernitz\anaconda3\envs\fqseg\lib\site-packages\segwrap\utils_cellpose.py", line 85, in cellpose_predict masks, flows, styles, diams = model.eval(imgs, diameter=obj_size, channels=channels, net_avg=False, threshold=0.4) File "c:\users\jbernitz\anaconda3\envs\fqseg\lib\site-packages\cellpose\models.py", line 157, in eval threshold=0.4) File "c:\users\jbernitz\anaconda3\envs\fqseg\lib\site-packages\cellpose\models.py", line 320, in eval img = np.transpose(img, (1,2,0)) File "c:\users\jbernitz\anaconda3\envs\fqseg\lib\site-packages\numpy\core\fromnumeric.py", line 639, in transpose return _wrapfunc(a, 'transpose', axes) File "c:\users\jbernitz\anaconda3\envs\fqseg\lib\site-packages\numpy\core\fromnumeric.py", line 56, in _wrapfunc return getattr(obj, method)(*args, **kwds) ValueError: axes don't match array.
```

Finally, if I specify a size for the image (512, 512), I get the following error: 
```
{ "type": "SegmentCellsNuclei", "path_scan": "N:\\schroeder\\Data\\JMB\\2020\\201007 Gata1 test 13\\Images\\Raw\\Stacks", "input_subfolder": "", "path_save": "N:\\schroeder\\Data\\JMB\\2020\\201007 Gata1 test 13\\Images\\Analysis\\Segmentation", "str_cyto": "c03", "str_nuclei": "c01", "new_size": "512, 512", "size_cells": 140, "size_nuclei": 90, "img_ext": ".tif" }

Function (segment_obj_indiv) called with: {'path_scan': 'N:\\schroeder\\Data\\JMB\\2020\\201007 Gata1 test 13\\Images\\Raw\\Stacks', 'strings': ('c03', 'c01'), 'img_ext': '.tif', 'new_size': (512, 512), 'sizes': (140, 90), 'models': ('cyto', 'nuclei'), 'path_save': 'N:\\schroeder\\Data\\JMB\\2020\\201007 Gata1 test 13\\Images\\Analysis\\Segmentation', 'input_subfolder': '', 'callback_log': '<function RPC._gen_remote_method.<locals>.remote_method at 0x000001FECBE8DC18>', 'callback_status': '<function RPC._gen_remote_method.<locals>.remote_method at 0x000001FECBE84048>', 'callback_progress': '<function RPC._gen_remote_method.<locals>.remote_method at 0x000001FECBE8DF78>'}

CellPose will be USING CPU

Loading image pairs and segment them on the fly

Loading images and segment them on the fly

Segmenting image : 201009_MkPsFull_p001_c03.tif

Error: Error: Traceback (most recent call last): File "<ipython-input-2-d3ee6e66ac6a>", line 87, in run callback_progress=api.showProgress) File "c:\users\jbernitz\anaconda3\envs\fqseg\lib\site-packages\segwrap\utils_cellpose.py", line 406, in segment_cells_nuclei_indiv img_cyto = resize(img_cyto, new_size) File "c:\users\jbernitz\anaconda3\envs\fqseg\lib\site-packages\skimage\transform\_warps.py", line 124, in resize raise ValueError("len(output_shape) cannot be smaller than the image " ValueError: len(output_shape) cannot be smaller than the image dimensions
```
Any help is much appreciated. I'm working on Windows 10 with a 64-bit OS and x64-based processor. I've updated the SegmentCellNuclei plugin (ver 0.1.9), and below are the packages I have in the conda environment I'm using to launch the jupyter engine. Let me know if you need more information.

```
# Name                    Version                   Build  Channel
aiohttp                   3.6.2                    pypi_0    pypi
argon2-cffi               20.1.0                   pypi_0    pypi
async-generator           1.10                     pypi_0    pypi
async-timeout             3.0.1                    pypi_0    pypi
attrs                     20.2.0                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
big-fish                  0.4.0                    pypi_0    pypi
bleach                    3.2.1                    pypi_0    pypi
ca-certificates           2020.6.20            hecda079_0    conda-forge
cellpose                  0.0.1.25                 pypi_0    pypi
certifi                   2020.6.20        py37hc8dfbb8_0    conda-forge
cffi                      1.14.3                   pypi_0    pypi
chardet                   3.0.4                    pypi_0    pypi
cloudpickle               1.6.0                    pypi_0    pypi
colorama                  0.4.3                    pypi_0    pypi
cycler                    0.10.0                   pypi_0    pypi
dask                      2.29.0                   pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
defusedxml                0.6.0                    pypi_0    pypi
elfinder-client           2.1.55a6                 pypi_0    pypi
entrypoints               0.3                      pypi_0    pypi
freetype                  2.10.2               hd328e21_0    conda-forge
hupper                    1.10.2                   pypi_0    pypi
idna                      2.6                      pypi_0    pypi
imageio                   2.9.0                    pypi_0    pypi
imjoy                     0.10.10                  pypi_0    pypi
imjoy-elfinder            0.1.60                   pypi_0    pypi
imjoy-jupyter-extension   0.2.11                   pypi_0    pypi
imjoy-rpc                 0.2.30                   pypi_0    pypi
importlib-metadata        2.0.0                    pypi_0    pypi
ipykernel                 5.3.4                    pypi_0    pypi
ipython                   7.18.1                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                7.5.1                    pypi_0    pypi
jedi                      0.17.2                   pypi_0    pypi
jinja2                    2.11.2                   pypi_0    pypi
jpeg                      9d                   he774522_0    conda-forge
jsonschema                3.2.0                    pypi_0    pypi
jupyter                   1.0.0                    pypi_0    pypi
jupyter-client            6.1.7                    pypi_0    pypi
jupyter-console           6.2.0                    pypi_0    pypi
jupyter-core              4.6.3                    pypi_0    pypi
jupyter-server-proxy-windows 1.5.1                    pypi_0    pypi
jupyterlab-pygments       0.1.1                    pypi_0    pypi
kiwisolver                1.2.0                    pypi_0    pypi
libpng                    1.6.37               ha81a0f5_2    conda-forge
libtiff                   4.1.0                h885aae3_6    conda-forge
llvmlite                  0.34.0                   pypi_0    pypi
lz4-c                     1.9.2                h62dcd97_2    conda-forge
markupsafe                1.1.1                    pypi_0    pypi
matplotlib                3.0.2                    pypi_0    pypi
mistune                   0.8.4                    pypi_0    pypi
mrc                       0.1.5                    pypi_0    pypi
multidict                 4.7.6                    pypi_0    pypi
mxnet-mkl                 1.5.0                    pypi_0    pypi
natsort                   7.0.1                    pypi_0    pypi
nbclient                  0.5.0                    pypi_0    pypi
nbconvert                 6.0.6                    pypi_0    pypi
nbformat                  5.0.7                    pypi_0    pypi
nest-asyncio              1.4.0                    pypi_0    pypi
networkx                  2.5                      pypi_0    pypi
notebook                  6.1.4                    pypi_0    pypi
numba                     0.51.2                   pypi_0    pypi
numpy                     1.16.0                   pypi_0    pypi
olefile                   0.46                       py_0    conda-forge
opencv-python             4.4.0.44                 pypi_0    pypi
openssl                   1.1.1h               he774522_0    conda-forge
packaging                 20.4                     pypi_0    pypi
pandas                    0.24.0                   pypi_0    pypi
pandocfilters             1.4.2                    pypi_0    pypi
parso                     0.7.1                    pypi_0    pypi
pastedeploy               2.1.0                    pypi_0    pypi
pathvalidate              2.3.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    7.2.0                    pypi_0    pypi
pip                       20.2.2                   py37_0
plaster                   1.0                      pypi_0    pypi
plaster-pastedeploy       0.7                      pypi_0    pypi
prometheus-client         0.8.0                    pypi_0    pypi
prompt-toolkit            3.0.7                    pypi_0    pypi
pycparser                 2.20                     pypi_0    pypi
pygments                  2.7.1                    pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
pyramid                   1.10.4                   pypi_0    pypi
pyramid-jinja2            2.8                      pypi_0    pypi
pyrsistent                0.17.3                   pypi_0    pypi
python                    3.7.9                h60c2a47_0
python-dateutil           2.8.1                    pypi_0    pypi
python-graphviz           0.8.4                    pypi_0    pypi
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2020.1                   pypi_0    pypi
pywavelets                1.1.1                    pypi_0    pypi
pywin32                   228                      pypi_0    pypi
pywinpty                  0.5.7                    pypi_0    pypi
pyyaml                    5.3.1                    pypi_0    pypi
pyzmq                     19.0.2                   pypi_0    pypi
qtconsole                 4.7.7                    pypi_0    pypi
qtpy                      1.9.0                    pypi_0    pypi
requests                  2.18.4                   pypi_0    pypi
scikit-image              0.14.2                   pypi_0    pypi
scikit-learn              0.20.2                   pypi_0    pypi
scipy                     1.4.1                    pypi_0    pypi
segwrap                   0.0.1.6                  pypi_0    pypi
send2trash                1.5.0                    pypi_0    pypi
setuptools                49.6.0                   py37_0
simpervisor               0.3                      pypi_0    pypi
six                       1.15.0                   pypi_0    pypi
sqlite                    3.33.0               h2a8f88b_0
terminado                 0.9.1                    pypi_0    pypi
testpath                  0.4.4                    pypi_0    pypi
tifffile                  2020.9.22                pypi_0    pypi
tk                        8.6.10               he774522_0    conda-forge
toolz                     0.11.1                   pypi_0    pypi
tornado                   6.0.4                    pypi_0    pypi
tqdm                      4.49.0                   pypi_0    pypi
traitlets                 5.0.4                    pypi_0    pypi
translationstring         1.4                      pypi_0    pypi
typing-extensions         3.7.4.3                  pypi_0    pypi
urllib3                   1.22                     pypi_0    pypi
vc                        14.1                 h0510ff6_4
venusian                  3.0.0                    pypi_0    pypi
vs2015_runtime            14.16.27012          hf0eaf9b_3
waitress                  1.4.4                    pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
webob                     1.8.6                    pypi_0    pypi
werkzeug                  1.0.1                    pypi_0    pypi
wheel                     0.35.1                     py_0
widgetsnbextension        3.5.1                    pypi_0    pypi
wincertstore              0.2                      py37_0
xz                        5.2.5                h62dcd97_1    conda-forge
yarl                      1.6.0                    pypi_0    pypi
zipp                      3.2.0                    pypi_0    pypi
zlib                      1.2.11               h62dcd97_4
zope-deprecation          4.4.0                    pypi_0    pypi
zope-interface            5.1.0                    pypi_0    pypi
zstd                      1.4.5                h1f3a1b7_2    conda-forge
```

**Comment by muellerflorian** [comment]
Thanks for the detailed report. I will have a look right away. Will keep you posted.

**Comment by muellerflorian** [comment]
I just tried it on some test-data & could unfortunately not reproduce the error. 

Some of the error messages mention memory issues or array sizes.  Are the images that you try to segment 2D? If yes, maybe you could send me a test example, then I could try to run the code on your images directly (muellerf.research@gmail.com).

**Comment by jbernitz** [comment]
When I looked back at the code, I was trying to segment using the image stacks instead of the projections. Unfortunately, when I run using the image projections, I a new set of errors

When I run with no specified new_size, or with (512, 512) specified, I get new errors:
```
{ "type": "SegmentCellsNuclei", "path_scan": "paste-path-to-data", "input_subfolder": "segmentation-input", "path_save": "segmentation-input˃˃segmentation-results", "str_cyto": "cy3", "str_nuclei": "dapi", "new_size": "2", "size_cells": 100, "size_nuclei": 50, "img_ext": ".png" }

{ "type": "SegmentCellsNuclei", "path_scan": "C:\\Test\\Images\\Raw\\Projections\\test\\200925 Segmentations\\Raw Images", "input_subfolder": "", "path_save": "C:\\Test\\Images\\Raw\\Projections\\test\\200925 Segmentations\\New_SegmentCellsNuclei_results", "str_cyto": "c03", "str_nuclei": "c01", "new_size": "", "size_cells": 140, "size_nuclei": 90, "img_ext": ".tif" }

Function (segment_obj_indiv) called with: {'path_scan': 'C:\\Test\\Images\\Raw\\Projections\\test\\200925 Segmentations\\Raw Images', 'strings': ('c03', 'c01'), 'img_ext': '.tif', 'new_size': (), 'sizes': (140, 90), 'models': ('cyto', 'nuclei'), 'path_save': 'C:\\Test\\Images\\Raw\\Projections\\test\\200925 Segmentations\\New_SegmentCellsNuclei_results', 'input_subfolder': '', 'callback_log': '<function RPC._gen_remote_method.<locals>.remote_method at 0x000001C306D79C18>', 'callback_status': '<function RPC._gen_remote_method.<locals>.remote_method at 0x000001C306D99048>', 'callback_progress': '<function RPC._gen_remote_method.<locals>.remote_method at 0x000001C306D79F78>'}

CellPose will be USING CPU

Loading image pairs and segment them on the fly

Loading images and segment them on the fly

Segmenting image : 201009_MkPsFull_p001_c03.tif

Performing segmentation of cells

Creating outputs ...

Error: Error: Traceback (most recent call last): File "<ipython-input-2-d3ee6e66ac6a>", line 87, in run callback_progress=api.showProgress) File "c:\users\jbernitz\anaconda3\envs\fqseg\lib\site-packages\segwrap\utils_cellpose.py", line 434, in segment_cells_nuclei_indiv cellpose_predict(data_cyto, config_cyto, path_save=path_save_results, callback_log=callback_log) File "c:\users\jbernitz\anaconda3\envs\fqseg\lib\site-packages\segwrap\utils_cellpose.py", line 107, in cellpose_predict plot.show_segmentation(fig, imgi_rescale.astype('uint8'), maski, flowi, channels=channels) File "c:\users\jbernitz\anaconda3\envs\fqseg\lib\site-packages\cellpose\plot.py", line 51, in show_segmentation ax.imshow(img0) File "c:\users\jbernitz\anaconda3\envs\fqseg\lib\site-packages\matplotlib\__init__.py", line 1810, in inner return func(ax, *args, **kwargs) File "c:\users\jbernitz\anaconda3\envs\fqseg\lib\site-packages\matplotlib\axes\_axes.py", line 5494, in imshow im.set_data(X) File "c:\users\jbernitz\anaconda3\envs\fqseg\lib\site-packages\matplotlib\image.py", line 646, in set_data raise TypeError("Invalid dimensions for image data") TypeError: Invalid dimensions for image data
```
If I specify the value 4 for new_size:
```
{ "type": "SegmentCellsNuclei", "path_scan": "N:\\schroeder\\Data\\JMB\\2020\\201007 Gata1 test 13\\Images\\Raw\\Projections", "input_subfolder": "", "path_save": "N:\\schroeder\\Data\\JMB\\2020\\201007 Gata1 test 13\\Images\\Analysis\\Segmentation", "str_cyto": "c03", "str_nuclei": "c01", "new_size": "4", "size_cells": 140, "size_nuclei": 90, "img_ext": ".tif" }

Function (segment_obj_indiv) called with: {'path_scan': C:\\Test\\Images\\Raw\\Projections\\test\\200925 Segmentations\\Raw Images', 'strings': ('c03', 'c01'), 'img_ext': '.tif', 'new_size': (4,), 'sizes': (140, 90), 'models': ('cyto', 'nuclei'), 'path_save': 'C:\\Test\\Images\\Raw\\Projections\\test\\200925 Segmentations\\New_SegmentCellsNuclei_results', 'input_subfolder': '', 'callback_log': '<function RPC._gen_remote_method.<locals>.remote_method at 0x000001C306D79C18>', 'callback_status': '<function RPC._gen_remote_method.<locals>.remote_method at 0x000001C306D99048>', 'callback_progress': '<function RPC._gen_remote_method.<locals>.remote_method at 0x000001C306D79F78>'}

CellPose will be USING CPU

Loading image pairs and segment them on the fly

Loading images and segment them on the fly

Segmenting image : 201009_MkPsFull_p001_c03.tif

Performing segmentation of cells

Error: Error: Traceback (most recent call last): File "<ipython-input-2-d3ee6e66ac6a>", line 87, in run callback_progress=api.showProgress) File "c:\users\jbernitz\anaconda3\envs\fqseg\lib\site-packages\segwrap\utils_cellpose.py", line 434, in segment_cells_nuclei_indiv cellpose_predict(data_cyto, config_cyto, path_save=path_save_results, callback_log=callback_log) File "c:\users\jbernitz\anaconda3\envs\fqseg\lib\site-packages\segwrap\utils_cellpose.py", line 85, in cellpose_predict masks, flows, styles, diams = model.eval(imgs, diameter=obj_size, channels=channels, net_avg=False, threshold=0.4) File "c:\users\jbernitz\anaconda3\envs\fqseg\lib\site-packages\cellpose\models.py", line 157, in eval threshold=0.4) File "c:\users\jbernitz\anaconda3\envs\fqseg\lib\site-packages\cellpose\models.py", line 296, in eval x = [transforms.reshape(x[i], channels=channels[i], invert=invert) for i in range(nimg)] File "c:\users\jbernitz\anaconda3\envs\fqseg\lib\site-packages\cellpose\models.py", line 296, in <listcomp> x = [transforms.reshape(x[i], channels=channels[i], invert=invert) for i in range(nimg)] File "c:\users\jbernitz\anaconda3\envs\fqseg\lib\site-packages\cellpose\transforms.py", line 215, in reshape data = data[:,:,chanid] IndexError: index 0 is out of bounds for axis 2 with size 0
```

However, if I specify a new_size of 2, which is the automatic value, the code runs but it produces only black images as output with no succesful segmentation.  This is true for both new data that I have not segmented before, and old data that was successfully segmented previously. I'll send an email with example data and results.

**Comment by muellerflorian** [comment]
For reference. We identified two issues that should now be corrected. 

1. Segmentation is only done on 2d images. however, 3D images can erroneously be provided. With #22 input size is now checked. 
2. Code was executed in a conda env with a pinned version of ski-image (14), which caused issues in resizing and saving. Pinning the version to 17 (#20) resolved this issue.
